apiVersion: v1
kind: Service
metadata:
  name: console-object-store-headless
  namespace: console-object-store
  labels:
    app.kubernetes.io/name: seaweedfs-s3
    app.kubernetes.io/instance: console-object-store
    app.kubernetes.io/part-of: console-object-store
    console.nousresearch.com/dark-stage: "true"
    console.nousresearch.com/context: "onprem"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: s3
      port: 8333
      targetPort: s3
      protocol: TCP
      appProtocol: http
  selector:
    app.kubernetes.io/name: seaweedfs-s3
    app.kubernetes.io/instance: console-object-store
---
apiVersion: v1
kind: Service
metadata:
  name: console-object-store-s3
  namespace: console-object-store
  labels:
    app.kubernetes.io/name: seaweedfs-s3
    app.kubernetes.io/instance: console-object-store
    app.kubernetes.io/part-of: console-object-store
    console.nousresearch.com/dark-stage: "true"
    console.nousresearch.com/context: "onprem"
  annotations:
    console.nousresearch.com/s3-endpoint-url: "http://console-object-store-s3.console-object-store.svc.cluster.local:8333"
    console.nousresearch.com/s3-addressing-style: "path"
spec:
  type: ClusterIP
  ports:
    - name: s3
      port: 8333
      targetPort: s3
      protocol: TCP
      appProtocol: http
  selector:
    app.kubernetes.io/name: seaweedfs-s3
    app.kubernetes.io/instance: console-object-store
