#!/usr/bin/env bash
# Materialize mode-0600 .buckconfig.local with the NativeLink RE client block.
# Never commits (.buckconfig.local is gitignored).
#
# [buck2_re_client] is daemon-startup config: buck2 reads it when the daemon
# starts, so it CANNOT be supplied via --config-file (that path fails with
# "Error: (No engine address)"). It must live in .buckconfig / .buckconfig.local.
#
# Usage:
#   scripts/cas/materialize-buckconfig-local.sh                        # lab writer, mTLS
#   scripts/cas/materialize-buckconfig-local.sh --role reader
#   scripts/cas/materialize-buckconfig-local.sh --profile gha --role writer
#   scripts/cas/materialize-buckconfig-local.sh --endpoint 100.64.0.5:50051 --no-tls
#
# Profiles (endpoint defaults):
#   lab     writer 127.0.0.1:50051   reader 127.0.0.1:50052
#   gha     writer 127.0.0.1:55051   reader 127.0.0.1:55052   (Access TCP / mesh forwarder)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ROLE="writer"
PROFILE="lab"
ENDPOINT=""
USE_TLS=1
TLS_DIR="${OYA_CAS_TLS_DIR:-$HOME/oyatie-cas/tls}"
INSTANCE="${OYA_CAS_INSTANCE:-main}"
OUT="${ROOT}/.buckconfig.local"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --role) ROLE="$2"; shift 2 ;;
    --profile) PROFILE="$2"; shift 2 ;;
    --endpoint) ENDPOINT="$2"; shift 2 ;;
    --instance) INSTANCE="$2"; shift 2 ;;
    --tls-dir) TLS_DIR="$2"; shift 2 ;;
    --no-tls) USE_TLS=0; shift ;;
    --out) OUT="$2"; shift 2 ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

case "$ROLE" in writer|reader) ;; *) echo "role must be writer|reader" >&2; exit 2 ;; esac

# Ports are derived from the same variables start-access-tcp.sh honours. Hard-coding
# them lets a forwarder bind one port while Buck2 dials another, and every cache
# request then fails.
LAB_WRITE_PORT="${CAS_LOCAL_WRITE_PORT:-50051}"
LAB_READ_PORT="${CAS_LOCAL_READ_PORT:-50052}"
GHA_WRITE_PORT="${CAS_LOCAL_WRITE_PORT:-55051}"
GHA_READ_PORT="${CAS_LOCAL_READ_PORT:-55052}"

if [[ -z "$ENDPOINT" ]]; then
  case "${PROFILE}:${ROLE}" in
    lab:writer) ENDPOINT="127.0.0.1:${LAB_WRITE_PORT}" ;;
    lab:reader) ENDPOINT="127.0.0.1:${LAB_READ_PORT}" ;;
    gha:writer) ENDPOINT="127.0.0.1:${GHA_WRITE_PORT}" ;;
    gha:reader) ENDPOINT="127.0.0.1:${GHA_READ_PORT}" ;;
    *) echo "unknown profile: $PROFILE (expected lab|gha)" >&2; exit 2 ;;
  esac
fi

if (( USE_TLS )); then
  SCHEME="grpcs"
  case "$ROLE" in
    writer) CERT="$TLS_DIR/client-writer.crt"; KEY="$TLS_DIR/client-writer.key" ;;
    reader) CERT="$TLS_DIR/client-reader.crt"; KEY="$TLS_DIR/client-reader.key" ;;
  esac
  CA="$TLS_DIR/ca.crt"
  for f in "$CA" "$CERT" "$KEY"; do
    [[ -f "$f" ]] || { echo "missing TLS material: $f" >&2; exit 1; }
  done
else
  SCHEME="grpc"
fi

umask 077
{
  echo "# GENERATED by scripts/cas/materialize-buckconfig-local.sh -- do not commit."
  echo "# profile=${PROFILE} role=${ROLE} endpoint=${ENDPOINT} tls=${USE_TLS}"
  echo
  if [[ "$ROLE" == "writer" ]]; then
    echo "[buck2]"
    echo "  default_allow_cache_upload = true"
    echo
  fi
  echo "[buck2_re_client]"
  echo "  engine_address = ${SCHEME}://${ENDPOINT}"
  echo "  cas_address = ${SCHEME}://${ENDPOINT}"
  echo "  action_cache_address = ${SCHEME}://${ENDPOINT}"
  echo "  instance_name = ${INSTANCE}"
  if (( USE_TLS )); then
    echo "  tls = true"
    echo "  tls_ca_certs = ${CA}"
    echo "  tls_client_cert = ${CERT}"
    echo "  tls_client_key = ${KEY}"
  else
    echo "  tls = false"
  fi
} >"$OUT"
chmod 600 "$OUT"
echo "wrote ${OUT} (profile=${PROFILE} role=${ROLE} endpoint=${ENDPOINT} tls=${USE_TLS}; mode $(stat -f '%Lp' "$OUT" 2>/dev/null || stat -c '%a' "$OUT"))"
